sudo: required
language: generic

services:
  - docker

env:
  global:
    # Reemplazar con tu nombre de usuario real de Docker Hub
    DOCKER_USERNAME: nahuelolea2

before_install:
  - docker build -t nahuelolea2/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true nahuelolea2/react-test npm test

after_success:
  - docker build -t nahuelolea2/multi-client ./client
  - docker build -t nahuelolea2/multi-nginx ./nginx
  - docker build -t nahuelolea2/multi-server ./server
  - docker build -t nahuelolea2/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push nahuelolea2/multi-client
  - docker push nahuelolea2/multi-nginx
  - docker push nahuelolea2/multi-server
  - docker push nahuelolea2/multi-worker
